spring.application.name=nutricare

# Configurazione del database MySql
spring.datasource.url=jdbc:mysql://localhost:3306/nutricare?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
spring.datasource.username=nutricare
spring.datasource.password=nutricare92!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Impostazioni JPA
spring.jpa.hibernate.ddl-auto=none  
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Configurazione di Liquibase
spring.liquibase.change-log=classpath:db/changelog/changelog-master.xml
spring.liquibase.enabled=true

# Abilitare il logging SQL
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

