# Console H2 abilitata solo in sviluppo
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# SQL visibile in sviluppo
spring.jpa.show-sql=true
logging.level.com.angeloni.nutricare=DEBUG
