#Cors
cors.allowed.origin=http://localhost:4200

# Configurazione Database
spring.datasource.url=jdbc:mysql://localhost:3306/nutricare?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
spring.datasource.username=nutricare
spring.datasource.password=nutricare92!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configurazione JPA/Hibernate 
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Configurazione Liquibase
spring.liquibase.change-log=classpath:db/changelog/changelog-master.xml
spring.liquibase.enabled=true
spring.liquibase.default-schema=nutricare 

# Configurazione Artemis
spring.artemis.mode=native
spring.artemis.broker-url=tcp://localhost:61616
spring.artemis.user=artemis-nutricare
spring.artemis.password=artemis-nutricare1
# Artemis queue
jms.queue.diet.start=app.diet.start

# Configurazione Email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=angeloni.nutricare@gmail.com
spring.mail.password=Angeloni_nutricare92
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#Server
server.host=http://localhost
server.port=8080
server.servlet.context-path=/api/nutricare

#JWT Token
jwt.secret=b3JkaW5hcnlxdWlldGNvcm5jb3VudHByb2dyZXNzYWNjb3VudHF1aWV0aGVhbHRoZ2lybGhlYXZ5dHJhZmZpY2Nvb2tpZXN0b3VjaGltcG9ydGFuY2VmaWZ0ZWVuc2VjdGlvbnNwZWxsd2ludGVycXVpdGVza2lsbHBhdHRlcm5maW5hbG9mZmljaWFsbWVhbGZpbmVzdGxpZ2h0aGVsZGNvdW50bGl0dGxlZ292ZXJubWVudGNoYW5nZWZlZXRza2luYWxvbmdsZWZ0ZmVuY2VyZWFzb25kZXNrZHVyaW5naXNsYW5kbWF0ZXJpYWxuZWdhdGl2ZXRpdGxlbGlxdQ==

