package com.angeloni.nutricare.enums;

public enum AIModelEnum {

    // OpenAI / ChatGPT
    GPT4O("GPT4O"),
    GPT4O_MINI("GPT4O_MINI"),
    GPT4TURBO("GPT4TURBO"),
    GPT4("GPT4"),
    GPT3TURBO("GPT3TURBO"),
    OPENAIO1("OPENAIO1"),
    OPENAIO1MINI("OPENAIO1MINI"),
    OPENAIO3("OPENAIO3"),
    OPENAIO3MINI("OPENAIO3MINI"),
    OPENAIO4MINI("OPENAIO4MINI"),

    // Anthropic / Claude
    CLAUDE5FABLE("CLAUDE5FABLE"),
    CLAUDE5SONNET("CLAUDE5SONNET"),
    CLAUDE4SONNET("CLAUDE4SONNET"),
    CLAUDE48OPUS("CLAUDE48OPUS"),
    CLAUDE4OPUS("CLAUDE4OPUS"),
    CLAUDE37SONNET("CLAUDE37SONNET"),
    CLAUDE35SONNET("CLAUDE35SONNET"),
    CLAUDE35HAIKU("CLAUDE35HAIKU"),
    CLAUDE45HAIKU("CLAUDE45HAIKU"),
    CLAUDE3OPUS("CLAUDE3OPUS"),
    CLAUDE3SONNET("CLAUDE3SONNET"),
    CLAUDE3HAIKU("CLAUDE3HAIKU"),

    // Google Gemini
    GEMINI_25_PRO("GEMINI_25_PRO"),
    GEMINI_25_FLASH("GEMINI_25_FLASH"),
    GEMINI_20_FLASH("GEMINI_20_FLASH"),
    GEMINI_20_FLASH_LITE("GEMINI_20_FLASH_LITE"),
    GEMINI_15_FLASH("GEMINI_15_FLASH"),
    GEMINI_15_PRO("GEMINI_15_PRO");

    private final String value;

    AIModelEnum(String value) {
        this.value = value;
    }

    public String getValue() {
        return value;
    }
}
