INSERT INTO ai (id, name, model)
VALUES 
(1, 'CHATGPT', 'GPT4O'),
(2, 'CHATGPT', 'OPENAIO1'),
(4, 'CLAUDE', 'CLAUDE3SONNET'),
(5, 'CLAUDE', 'CLAUDE35SONNET'),
(6, 'GITHUB_COPILOT', 'COPILOT_GPT4O');

